# NUMPY

NumPy is a Python library that is the core library for scientific computing in Python. It contains a collection of tools and techniques that can be used to solve on a computer mathematical models of problems in Science and Engineering. One of these tools is a high-performance multidimensional array object that is a powerful data structure for efficient computation of arrays and matrices. To work with these arrays, there’s a vast amount of high-level mathematical functions operate on these matric

#### Arrays can store data very compactly and are more efficient for storing large amounts of data. Arrays are great for numerical operations; lists cannot directly handle math operations

# Difference Btwn List and array

#### A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 

#### A list is the Python equivalent of an array, but is resizeable and can contain elements of different types.

# In List we can pass different datatypes but in array we can only give similar Datatypes

# Creating Array

In [1]:
import numpy as np

In [3]:
#with list
arr = np.array([1,2,4,6,8])

arr

array([1, 2, 4, 6, 8])

In [4]:
li = [1,2,3]
np.array(li)

array([1, 2, 3])

In [5]:
#check data type
type(arr),type(li)

(numpy.ndarray, list)

In [6]:
# with tuple
arr = np.array((1, 2, 3, 4, 5))

arr

array([1, 2, 3, 4, 5])

In [6]:
#add list into np
lis=[1,2,4,6,8]

arr=np.array(lis)
arr

array([1, 2, 4, 6, 8])

In [6]:
arr


array([1, 2, 4, 6, 8])

In [10]:
#Return a new array of given shape and type, with random values..
a = np.empty([2,3], dtype = int) 
a

array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
#The numpy.ones() function returns a new array of given shape and type, with ones.
a = np.zeros(4, dtype = int) 
a

array([0, 0, 0, 0])

In [14]:
a = np.zeros((5,3), dtype = int) 
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
#create array with ones
a = np.ones(5, dtype = int) 
a

array([1, 1, 1, 1, 1])

In [19]:
#create array with range
a = np.arange(100) 
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

 Returns an array with evenly spaced elements as per the interval. The interval mentioned is half opened i.e. [Start, Stop,step)

In [6]:
#with condition 
a = np.arange(10,100,5) 
a

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

The numpy.linspace() function returns number spaces evenly w.r.t interval. Similar to numpy.arange() function but instead of step it uses sample number.

In [5]:
#using line space, number of sample =5
a = np.linspace(10,100,5) 
a

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [ ]:
a = np.linspace

In [25]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


# Dimension

In [4]:
#Zero dimension
arr = np.array(42)

print(arr)
print(arr.ndim)

42
0


In [5]:
#one dimension
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(arr.ndim)

[1 2 3 4 5]
1


More than one dimension:

In [21]:
#Two dimension
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [22]:
#Three dimension

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

print(arr.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [6]:
#multiple dimension
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print(arr.ndim)


[[[[[1 2 3 4]]]]]
5


In [8]:
#random method to creat array
a = np.random.randint(100)
a

46

Random sampling in numpy | randint() function

In [9]:
a = np.random.randint(50, size=(3))

a

array([23, 40, 18])

In [10]:
a = np.random.rand(4)
a

array([0.20102569, 0.99696704, 0.20349131, 0.86844301])

In [15]:
2 ** 3

8

In [11]:
a = np.random.rand(2,5,3)

a

array([[[0.90392654, 0.299557  , 0.66978441],
        [0.44627021, 0.5669623 , 0.24941807],
        [0.0213843 , 0.65478441, 0.46290731],
        [0.64492127, 0.32811763, 0.47731511],
        [0.56509082, 0.56772876, 0.65079728]],

       [[0.3387686 , 0.97372015, 0.31887701],
        [0.96666074, 0.48062729, 0.98750379],
        [0.86438169, 0.69683593, 0.3006275 ],
        [0.001236  , 0.88252838, 0.91461971],
        [0.19866358, 0.21785089, 0.04334548]]])

Return one of the values in an array:

In [ ]:
np.random.rand

In [19]:

a = np.random.choice([1,2,60,4,40])

a

60

In [20]:
li = range(100)

Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9)

In [25]:
a = np.random.choice(li, size=(3,2))

a

array([[89, 64],
       [98, 36],
       [44, 33]])

# Data type

Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [26]:
#int
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [13]:
type(arr)

list

In [12]:
arr = [1, 2, 3, 4]

arr[1:3]

[2, 3]

In [51]:
#string
arr = np.array(['python', 'java', 'c'])

print(type(arr[0]))

<class 'numpy.str_'>


In [14]:
#convert data type
arr = np.array([12,16,21])

arr = np.array([12,16,21])
print(new_arr)

[12 16 21]


In [20]:
arr = np.array([12.2,16.3,21.5])

In [21]:
print(arr)

[12.2 16.3 21.5]


In [22]:
int_arr = np.array([12.2,16.3,21.5])

In [35]:
arr
anew_arr

array([12, 16, 21], dtype=int32)

In [15]:
print(arr)

[12 16 21]


In [23]:
new_arr = int_arr.astype('i')

In [24]:
print(new_arr)

[12 16 21]


In [17]:
print(new_arr)

[12. 16. 21.]


In [54]:
print(arr)
print(new_arr)
print(new_arr.dtype)

[12.3  16.34 21.34]
[12 16 21]
int32


In [25]:
arr = np.array([4, 0.2, 2])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True  True  True]
bool


# COPY Array

In [38]:
arr = np.array([10,20,30,40,50,60])
a = arr.copy()

In [31]:
a = arr

In [39]:
print(arr)
print(a)

[10 20 30 40 50 60]
[10 20 30 40 50 60]


In [40]:
arr[0] = 60

Make a view, change the original array, and display both arrays

In [43]:
#view, changing in view array affect orignal arrray

arr = np.array([10,20,30,40,50,70])
a = arr.view()
arr[0] = 60

In [44]:
print(arr)
print(a)

[60 20 30 40 50 70]
[60 20 30 40 50 70]


# Indexing & slicing

In [46]:
arr = np.array([10,20,30,40,50])

arr[4]

50

In [54]:

arr[2]

30

In [56]:
import numpy as np
arr = np.array([[10,20,30,40,50], [60,70,80,90,100]])
print(arr)
arr[0, 3]

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


40

In [61]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
arr[0, -2],arr[0, -3]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(4, 3)

In [68]:
list_ = [10,1,2]

In [70]:
list_[-1]

2

In [47]:
lis1=[1,2,3,4,5]
lis2=[2,3,4,5,6]
lis3=[9,7,6,8,9]

arr=np.array([lis1,lis2,lis3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [65]:
arr[1,1:3]


array([3, 4])

In [67]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [52]:
arr[1:,3:][0,1]

6

In [49]:
arr[0,1]

2

In [69]:
arr[0:2,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

# Shape

In [53]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

x = np.where(arr>7)
x

(array([1], dtype=int64), array([3], dtype=int64))

In [54]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [73]:
x = np.where(arr<5)

In [74]:
print(x)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [ ]:
np.where

In [58]:
print(x)

(array([1, 1, 1], dtype=int64), array([1, 2, 3], dtype=int64))


In [ ]:
np.where

In [75]:
print(x[0])

[0 0 0 0]


In [76]:
arr = np.array([[[1, 2, 3, 4],[2,6,7,9]],
                [[1, 2, 3, 4],[2,6,7,9]],
                [[1, 2, 3, 4],[2,6,7,9]]], ndmin=3)

print(arr)

[[[1 2 3 4]
  [2 6 7 9]]

 [[1 2 3 4]
  [2 6 7 9]]

 [[1 2 3 4]
  [2 6 7 9]]]


In [123]:
np.where(arr>=6,arr,-1)

array([-1, -1, -1,  7,  8, -1, -1,  9])

# Reshape

In [82]:
arr = np.array([1, 2, 3, 4, 5, 6, 10, 11, 12, 10, 11, 12])
print(arr)

print("     ")

new_arr = arr.reshape(4, 3)

print(new_arr)

[ 1  2  3  4  5  6 10 11 12 10 11 12]
     
[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]
 [10 11 12]]


In [89]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr)

newarr = arr.reshape(2,3,2)

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# iterating

In [84]:
li = [1,2,3,4]

In [85]:
for n in li:
    print("index",n)

index 1
index 2
index 3
index 4


In [86]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

for i in arr:
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [92]:
lis1=[1,2,3,4,5]
lis2=[2,3,4,5,6]
lis3=[9,7,6,8,9]

arr=np.array([lis1,lis2,lis3])
print(arr)
arr.ndim

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


2

In [89]:
for i in np.nditer(arr):
   print(i)

1
2
3
4
5
2
3
4
5
6
9
7
6
8
9


# Transpose  array

rotate array 

In [93]:

print(arr)

print("__________")

Tran_arry  = arr.T 

print(Tran_arry)


[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]
__________
[[1 2 9]
 [2 3 7]
 [3 4 6]
 [4 5 8]
 [5 6 9]]


# sorting 

In [94]:
arr = np.array([7,2,23,15,11])
print(arr)
print(np.sort(arr))

[ 7  2 23 15 11]
[ 2  7 11 15 23]


In [95]:
np.sort(arr)[::-1]

array([23, 15, 11,  7,  2])

In [103]:
#two dim array sort
arr = np.array([[20,10], [7,3]])

print(arr)
new_arr = np.sort(arr)        
new_arr

[[20 10]
 [ 7  3]]


array([[10, 20],
       [ 3,  7]])

In [120]:
#sorting by axis , row ,column
arr = np.array([[3,10,5], [20,7,23]])
print(arr)
new_arr = np.sort(arr, axis=0) 
new_arr

[[ 3 10  5]
 [20  7 23]]


array([[ 3,  7,  5],
       [20, 10, 23]])

In [ ]:
np.sort

# Searching

In [94]:
arr = np.array([2,2,5,7,8,2,5,9])



(array([1], dtype=int64), array([3], dtype=int64))


In [121]:
arr = np.array([2,2,5,7,8,2,5,9])

x = np.where(arr >= 5,"Okay","No")
print(x)


['No' 'No' 'Okay' 'Okay' 'Okay' 'No' 'Okay' 'Okay']


# Splitting 

In [97]:
arr = np.array([2,2,5,7,8,2,5,9,10])

newarr = np.array_split(arr, 4)

print(newarr)


[array([2, 2, 5]), array([7, 8]), array([2, 5]), array([ 9, 10])]


# joining

In [98]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])

arr = np.concatenate((arr, arr1))

print(arr)

[ 2  4  6  8 10 12]


In [127]:
arr = np.array([[2, 4], [6, 8]])

arr1 = np.array([[10, 12], [14, 16]])

arr = np.concatenate((arr, arr1), axis=1) 

arr

array([[ 2,  4, 10, 12],
       [ 6,  8, 14, 16]])

In [125]:
#try with 1
arr = np.array([[2, 4], [6, 8]])
print(arr)
arr1 = np.array([[10, 12], [14, 16]])

arr = np.concatenate((arr, arr1), axis=1)

arr

[[2 4]
 [6 8]]


array([[ 2,  4, 10, 12],
       [ 6,  8, 14, 16]])

In [103]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])

arr = np.hstack((arr, arr1))

arr


array([ 2,  4,  6,  8, 10, 12])

In [105]:

arr = np.array([2,4,6])

arr1 = np.array([8,10,12])

arr = np.vstack((arr, arr1))

arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [130]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])


arr = np.dstack((arr, arr1))

arr

array([[[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])

# String , arithmmetic , static opration

In [130]:
arr = np.array(["Usa","INDIA","RUSSIA"])

new_arr = np.char.lower(arr)



In [131]:
new_arr

array(['usa', 'india', 'russia'], dtype='<U6')

In [62]:
arr= np.char.join('&', 'FINGERTIPS')
arr

array('F&I&N&G&E&R&T&I&P&S', dtype='<U19')

In [63]:
arr = np.array([2.344,6.232,8.34,5,3.5,4.36]) 

np.around(arr) 

array([2., 6., 8., 5., 4., 4.])

In [64]:
np.around(arr, decimals = 1) 

array([2.3, 6.2, 8.3, 5. , 3.5, 4.4])

In [65]:
np.floor(arr)

array([2., 6., 8., 5., 3., 4.])

In [66]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])


In [67]:
np.add(arr,arr1) 

array([10, 14, 18])

In [68]:
np.subtract(arr,arr1) 

array([-6, -6, -6])

In [69]:
np.multiply(arr,arr1) 

array([16, 40, 72])

In [70]:
np.divide(arr1,arr)

array([4. , 2.5, 2. ])

In [71]:
np.power(arr,2) 

array([ 4, 16, 36], dtype=int32)

In [72]:
np.mod(arr1,arr) 

array([0, 2, 0], dtype=int32)

In [73]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


In [74]:
np.median(arr) 

6.5

In [75]:
np.mean(arr) 

6.5

In [165]:
import pandas as pd

In [177]:
list =[30,40]

In [178]:
list2 = [78,45]

In [179]:
print(list2.append(list))

None


In [180]:
list2

[78, 45, [30, 40]]

In [171]:
print(list3)

None


In [173]:
list1 = list.append([10])

In [160]:
list2 

In [ ]:
append

In [145]:
list1

In [148]:
print(list1)

None


In [76]:
np.average(arr) 

6.5

In [77]:
np.std(arr)

3.452052529534663

In [78]:
np.var(arr)

11.916666666666666