# NUMPY

NumPy is a Python library that is the core library for scientific computing in Python. It contains a collection of tools and techniques that can be used to solve on a computer mathematical models of problems in Science and Engineering. One of these tools is a high-performance multidimensional array object that is a powerful data structure for efficient computation of arrays and matrices. To work with these arrays, there’s a vast amount of high-level mathematical functions operate on these matric

#### Arrays can store data very compactly and are more efficient for storing large amounts of data. Arrays are great for numerical operations; lists cannot directly handle math operations

# Difference Btwn List and array

#### A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 

#### A list is the Python equivalent of an array, but is resizeable and can contain elements of different types.

# In List we can pass different datatypes but in array we can only give similar Datatypes

# Creating Array

In [1]:
import numpy as np

In [ ]:
#with list
arr = np.array([4,7.0,9.8,2,6])

arr

In [ ]:
#check data type
type(arr)

In [ ]:
# with tuple
arr = np.array((1, 2, 3, 4, 5))

arr

In [ ]:
#add list into np
lis=[1,2,4,6,8]

arr=np.array(lis)
arr

In [ ]:
arr


In [ ]:
#Return a new array of given shape and type, with random values..

a = np.zeroes([3,3], dtype = int) 
a

In [ ]:
#The numpy.ones() function returns a new array of given shape and type, with ones.
a = np.zeros(9) 
a

In [ ]:
a = np.zeros((5,2), dtype = int) 
a

In [ ]:
#create array with ones
a = np.ones((2,4)) 
a


In [ ]:
#create array with range
a = np.arange(4) 
a

 Returns an array with evenly spaced elements as per the interval. The interval mentioned is half opened i.e. [Start, Stop,step)

In [ ]:
#with condition 
a = np.arange(10,30,2) 
a

The numpy.linspace() function returns number spaces evenly w.r.t interval. Similar to numpy.arange() function but instead of step it uses sample number.

In [ ]:
#using line space, number of sample =5
a = np.linspace(0,15,6) 
a

# Dimension

In [ ]:
#Zero dimension
arr = np.array(2)
print(arr)
print(arr.ndim)

In [ ]:
#one dimension
arr = np.array([1, 2, 3, 4, 5])

print(arr[4])

print(arr.ndim)

More than one dimension:

In [ ]:
#Two dimension

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[0][1])
print(arr.ndim)

In [ ]:
#Three dimension

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr[0][1][2])

print(arr.ndim)

In [ ]:
#multiple dimension
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr[0][0][])
print(arr.ndim)


In [ ]:
#random method to creat array
a = np.random.rand(3)
a

Random sampling in numpy | randint() function

In [ ]:
a = np.random.randint(20, size=(4,3))

a

In [ ]:
a = np.random.rand(4)

a

In [ ]:
a = np.random.randint(2,2)

a


Return one of the values in an array:

In [ ]:

a = np.random.choice([1,2,3,4,5])

a

Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9)

In [ ]:
a = np.random.choice([3, 5, 7, 9])
m = np.random.choice([67, 55, 77, 97])

print(a,m)

# Data type

Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [ ]:
#int
arr = np.array([['jay', 2.0, 3, 4],[1.2,1.1,2.2,5.6]])

print(arr.dtype)

In [ ]:
#string
arr = np.array(['python', 'java', 'c'])

print(arr.dtype)

In [ ]:
#convert data type
arr = np.array([12.3,16.34,21.34])

new_arr = arr.astype('f')


In [ ]:
print(arr)
print(new_arr)
print(new_arr.dtype)

In [ ]:
arr = np.array([4, 0, 2])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

# COPY Array

In [ ]:
arr = np.array([10,20,30,40,50])
a = arr

In [ ]:
print(arr)
print(a)

Make a view, change the original array, and display both arrays

In [ ]:
#view, changing in view array affect orignal arrray

arr = np.array([10,20,30,40,50])
a = arr.view()
arr[0] = 34


In [ ]:
print(arr)
print(a)

# Indexing & slicing

In [ ]:
arr = np.array([10,20,30,40,50])

arr[0]

In [ ]:

arr[1]

In [ ]:
import numpy as np
arr = np.array([[10,20,30,40,50], [60,70,80,90,100]])
print(arr)
arr[0,1]

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
arr[0][-2]

In [ ]:
lis1=[1,2,3,4,5]
lis2=[2,3,4,5,6]
lis3=[9,7,6,8,9]

arr=np.array([lis1,lis2,lis3])
arr.ndim

In [ ]:
arr[:,2:4]


In [ ]:
arr[2:,3:]


In [ ]:
arr[:,3:]


# Shape

In [3]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr)
arr.shape


[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [4]:
arr = np.array([1, 2, 3, 4], ndmin=3)

print(arr)
arr.shape


[[[1 2 3 4]]]


(1, 1, 4)

In [6]:
arr=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
arr.shape

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


(2, 2, 3)

# Reshape

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13,14])
print(arr)

print(" ....................    ")

new_arr = arr.reshape(2,7,1)

print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 ....................    
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]
  [14]]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(arr)

newarr = arr.reshape(2, 2, 3)

print(newarr)

# iterating

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [24]:
lis1=[1,2,3,4,5]
lis2=[2,3,4,5,6]
lis3=[9,7,6,8,9]

arr=np.array([lis1,lis2,lis3])
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [25]:
for i in arr:
    print(i)

[1 2 3 4 5]
[2 3 4 5 6]
[9 7 6 8 9]


In [ ]:
lis1=[1,2,3,4,5]
lis2=[2,3,4,5,6]
lis3=[9,7,6,8,9]

arr=np.array([lis1,lis2,lis3])

In [26]:
for i in np.nditer(arr):
     print(i)

1
2
3
4
5
2
3
4
5
6
9
7
6
8
9


# Transpose  array

rotate array 

In [27]:

print(arr)

print("__________")

Tran_arry  = arr.T 

print(Tran_arry)


[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]
__________
[[1 2 9]
 [2 3 7]
 [3 4 6]
 [4 5 8]
 [5 6 9]]


# sorting 

In [28]:
arr = np.array([7,2,23,15,11])
print(arr)
print(np.sort(arr))

[ 7  2 23 15 11]
[ 2  7 11 15 23]


In [30]:
#two dim array sort
arr = np.array([[20,10], [3,7]])
print(arr)
print("................")
new_arr = np.sort(arr)        
new_arr

[[20 10]
 [ 3  7]]
................


array([[10, 20],
       [ 3,  7]])

In [36]:
#sorting by axis , row ,column
arr = np.array([[20,10], [3,7]])
print(arr)
print(".............")
new_arr = np.sort(arr, axis = 0) 
new_arr

[[20 10]
 [ 3  7]]
.............


array([[ 3,  7],
       [20, 10]])

# Searching

In [37]:
arr = np.array([2,2,5,7,8,2,5,9])

x = np.where(arr == 2)

print(x)

(array([0, 1, 5], dtype=int64),)


# Splitting 

In [43]:
arr = np.array([2,2,5,7,8,2,5,9,10,11,12,13,14])

newarr = np.array_split(arr, 6)

print(newarr)


[array([2, 2, 5]), array([7, 8]), array([2, 5]), array([ 9, 10]), array([11, 12]), array([13, 14])]


# joining

In [47]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])

arr = np.concatenate((arr, arr1), axis=0)

arr

array([ 2,  4,  6,  8, 10, 12])

In [56]:
arr = np.array([[2, 4], [6, 8]])

arr1 = np.array([[10, 12], [14, 16]])

arr = np.concatenate((arr, arr1), axis=1)

arr

array([[ 2,  4, 10, 12],
       [ 6,  8, 14, 16]])

In [54]:
arr1

array([[10, 12],
       [14, 16]])

In [ ]:
#try with 1
arr = np.array([[2, 4], [6, 8]])

arr1 = np.array([[10, 12], [14, 16]])

arr = np.concatenate((arr, arr1), axis=1)

arr

In [57]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])

arr = np.hstack((arr, arr1))

arr


array([ 2,  4,  6,  8, 10, 12])

In [58]:

arr = np.array([2,4,6])

arr1 = np.array([8,10,12])

arr = np.vstack((arr, arr1))

arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [59]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])


arr = np.dstack((arr, arr1))

arr

array([[[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])

# String , arithmmetic , static opration

In [63]:
arr = np.array(['usa', 'india', 'russia'])

new_arr = np.char.title(arr)

new_arr

array(['Usa', 'India', 'Russia'], dtype='<U6')

In [65]:
arr= np.char.join('@', 'FINGERTIPS')
arr

array('F@I@N@G@E@R@T@I@P@S', dtype='<U19')

In [66]:
arr = np.array([2.344,6.232,8.34,5,3.5,4.36]) 

np.around(arr) 

array([2., 6., 8., 5., 4., 4.])

In [68]:
np.around(arr, decimals = 2) 

array([2.34, 6.23, 8.34, 5.  , 3.5 , 4.36])

In [70]:
np.ceil(arr)

array([3., 7., 9., 5., 4., 5.])

In [71]:
arr = np.array([2,4,6])

arr1 = np.array([8,10,12])


In [72]:
np.add(arr,arr1) 

array([10, 14, 18])

In [73]:
np.subtract(arr,arr1) 

array([-6, -6, -6])

In [74]:
np.multiply(arr,arr1) 

array([16, 40, 72])

In [75]:
np.divide(arr1,arr)

array([4. , 2.5, 2. ])

In [76]:
np.power(arr,2) 

array([ 4, 16, 36], dtype=int32)

In [77]:
np.mod(arr1,arr) 

array([0, 2, 0])

In [78]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])


In [79]:
np.median(arr) 

6.5

In [80]:
np.mean(arr) 

6.5

In [81]:
np.average(arr) 

6.5

In [82]:
np.std(arr)

3.452052529534663

In [83]:
np.var(arr)

11.916666666666666